scalar.dl.client.server.host=localhost
scalar.dl.client.auditor.host=localhost
scalar.dl.client.auditor.enabled=true
scalar.dl.client.cert_holder_id=foo
scalar.dl.client.authentication.method=hmac
scalar.dl.client.entity.identity.hmac.secret_key=7672217a9973430ed1eb46f586c6cb59fa5bcde728fad0a8a6f1982cd66f897b
