scalar.dl.ledger.proof.enabled=true
scalar.dl.ledger.auditor.enabled=false

scalar.dl.ledger.authentication.method=hmac
scalar.dl.ledger.servers.authentication.hmac.secret_key=a17b66210c946ee0c3cc89aa2588647cdf39e62aba90d30a6ed34c2b1e988005
scalar.dl.ledger.authentication.hmac.cipher_key=6dfd3dacd9e2b35ce1916db112f425c6af0581bf0be834eff666c0d4bc966eac

scalar.db.storage=jdbc
scalar.db.contact_points=jdbc:postgresql://postgres/
scalar.db.username=postgres
scalar.db.password=postgres

scalar.db.isolation_level=SERIALIZABLE
