scalar.dl.ledger.proof.enabled=true
scalar.dl.ledger.auditor.enabled=false

scalar.dl.ledger.proof.private_key_path=/scalar/ledger-key.pem

scalar.db.storage=jdbc
scalar.db.contact_points=jdbc:postgresql://postgres/
scalar.db.username=postgres
scalar.db.password=postgres

scalar.db.isolation_level=SERIALIZABLE