scalar.dl.auditor.ledger.host=localhost
scalar.dl.auditor.private_key_path=/scalar/auditor-key.pem
scalar.db.storage=jdbc
scalar.db.contact_points=jdbc:postgresql://postgres/
scalar.db.username=postgres
scalar.db.password=postgres
